### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by devyntk** [firstwiki/firstwiki.github.io#11]
To retain the good things about being a wiki, most importantly, the easy access to information, I think a search function. It can be a simple as using the google `site:` tag in a google search, but it needs something, rather than forcing users to go hunting through menus and categories.

**Comment by virtuald** [comment]
Added google custom search to `/search/`, search box on all pages. It's a bit weird if you make the page small, but I think it's good enough until someone wants to do a big redesign on the site.
