### ISSUE TITLE
Create a linter for the frontmatter

### ISSUE THREAD

**Issue by virtuald** [firstwiki/firstwiki.github.io#15]
I'm thinking that we should create a JSON schema (or is there such a thing as a YAML schema?) and validate it against that... people keep messing it up and there's nothing telling them that they're doing it incorrectly.

**Comment by virtuald** [comment]
I can't personally do this until after kickoff.

**Comment by devyntk** [comment]
I have no experience with any sort of linter or schemes validation, so I probably can't help either, unless someone pointed me in the right direction.

**Comment by virtuald** [comment]
I have something that works, I'll push it to the repos tomorrow.

**Comment by virtuald** [comment]
Fixed and pushed to all relevant repos. Should hopefully make it easier for people to contribute correctly in the future.
